group:
  - repos: |
      SavitskayaYlia/astro-depended-1@dev
      SavitskayaYlia/astro-depended-2@dev
      SavitskayaYlia/astro-depended-1@main
      SavitskayaYlia/astro-depended-2@main    
    files: 
      - source: .github/
        dest: .github/ 
      - source: dags/
        dest: dags/
    exclude: |
      .github/sync_depended_projects_conf.yml
      dags/example/exampledag.py
    deleteOrphaned: true
