group:
  - repos: |
      SavitskayaYlia/astro-depended-1@dev
      SavitskayaYlia/astro-depended-2@dev
      SavitskayaYlia/astro-depended-1@main
      SavitskayaYlia/astro-depended-2@main
    exclude:
      - .gitignore
      #.astro/
      #airflow_settings.yaml
      - dags/
      - .github/sync_depended_projects_conf.yml
    files: 
      - .github/
      - README.md
      - dags/example/
      - tests/
      - Dockerfile
      - requirements.txt
    

      
